development:
  adapter: postgresql
  encoding: unicode
  database: vidalSuits
  pool: 5
  username: hugo
  password: ''

test:
  adapter: postgresql
  encoding: unicode
  database: vidalSuits_test
  pool: 5
  username: hugo
  password: ''

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev