# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4521f8a41d07f46077ea4be59973d525dac8197b33006408ccbb62ff8ca2625627896effe17319c61e992017c274c9b7bbe1e1af3fa1eb39427a15ab5907c2ff

test:
  secret_key_base: 41c895e4b19898e1d761fa579115fa018b4eebb543b8a28cce9859f45058b90c55f36d728b08e075e4a3556a10cee5e5b46ded7d68b02127525d3a1b7b11f1ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
